# -*- coding: utf-8 -*-
"""
Datensatz: Weltklasse-Pianistinnen - drei kuratierte Listen aus einem gemeinsamen Pool.

Jede Kuenstlerin ist genau EIN Eintrag mit einem Feld "lists" (Liste von Strings),
das bestimmt, in welchen Ansichten sie erscheint:
  "newcomers" -> "Top 25 Newcomerinnen - All-Time High 2026"   (Nachwuchs, im Aufstieg)
  "icons"     -> "Top 25 Alltime High 2026"                          (etablierte/legendaere Groessen)
  "current"   -> "Top 20 - Stand Juli 2026"                          (aktuelles redaktionelles Schlaglicht)

Wichtiger Hinweis zur Methodik (wird auch im Frontend angezeigt):
Eine objektive Weltrangliste gibt es im klassischen Musikbetrieb nicht. Alle drei Listen
sind redaktionelle, kuratierte Auswahllisten - keine amtlichen oder objektiven Rankings.
Ueberschneidungen zwischen den Listen sind beabsichtigt.

Felder je Eintrag:
  slug, name, flag, born, lists, bio, awards, focus,
  current_note (optional), official_url, official_label, youtube, wikipedia_title
"""

PIANISTS = [
    {
        "slug": "alexandra-dovgan", "name": "Alexandra Dovgan", "flag": "\U0001F1F7\U0001F1FA",
        "born": "2007 \u00b7 Moskau, Russland", "lists": ["newcomers", "current"],
        "bio": "Als Vierjährige begann sie zu spielen, mit fünf wurde sie an der Zentralen Musikschule des Moskauer Konservatoriums bei Mira Martschenko aufgenommen. Bereits mit acht Jahren wurde die stille Konzentration ihres Spiels von Kritikern bemerkt. 2018 eröffnete sie mit elf Jahren gemeinsam mit Denis Matsuev und Valery Gergiev das Mariinsky-Klavierfestival, ein Moment, der als ihr internationaler Durchbruch gilt.\n\nSeither ist sie an den großen Bühnen Europas zu Gast, von der Philharmonie de Paris bis zum Concertgebouw Amsterdam. Seit 2022 lebt sie mit ihrer Familie in Málaga, Spanien. 2024 erhielt sie den Prix Serdang, verliehen von Rudolf Buchbinder.",
        "awards": ["Grand Prix, Grand Piano Competition Moskau (2018)", "Moskauer Vladimir-Krainev-Wettbewerb", "Prix Serdang (2024)"],
        "focus": ["Mozart", "Chopin", "Schumann", "Beethoven"],
        "current_note": "Seit der Verleihung des Prix Serdang 2024 zählt sie zu den meistgebuchten jungen Solistinnen Europas; 2025/26 mit Debüts bei mehreren großen Orchestern.",
        "official_url": "https://worldmasterpianists.com/artist/alexandra-dovgan/", "official_label": "Künstlerprofil (World Master Pianists)",
        "youtube": "https://www.youtube.com/results?search_query=Alexandra+Dovgan+piano", "wikipedia_title": "Alexandra Dovgan",
    },
    {
        "slug": "eva-gevorgyan", "name": "Eva Gevorgyan", "flag": "\U0001F1F7\U0001F1FA\U0001F1E6\U0001F1F2",
        "born": "15. April 2004 \u00b7 Moskau", "lists": ["newcomers", "current"],
        "bio": "Die russisch-armenische Pianistin studiert am Moskauer Tschaikowsky-Konservatorium bei Natalia Trull sowie an der Reina-Sofía-Musikschule in Madrid. Sie war die jüngste Finalistin des Internationalen Chopin-Wettbewerbs 2021 in Warschau, obwohl sie erst 17 Jahre alt war, und hat seither Preise bei über 40 internationalen Wettbewerben gesammelt.\n\n2022 erschien ihr Debütalbum mit Werken von Skrjabin und Chopin beim traditionsreichen Label Melodiya. Kritiker heben besonders ihre technische Reife bei gleichzeitig jugendlicher Frische hervor.",
        "awards": ["2. Preis, Cliburn International Junior Piano Competition (2019)", "1. Preis, Cleveland International Piano Competition (2018)", "Jüngste Finalistin, Chopin-Wettbewerb Warschau (2021)"],
        "focus": ["Chopin", "Skrjabin", "Brahms", "Rachmaninow"],
        "current_note": "Nach dem Chopin-Finale 2021 kontinuierlich wachsende internationale Konzerttätigkeit.",
        "official_url": "https://www.camimusic.com/eva-gevorgyan", "official_label": "Künstlerprofil (Columbia Artists)",
        "youtube": "https://www.youtube.com/results?search_query=Eva+Gevorgyan+piano", "wikipedia_title": "Eva Gevorgyan",
    },
    {
        "slug": "sophia-liu", "name": "Sophia Liu", "flag": "\U0001F1E8\U0001F1E6",
        "born": "2008 \u00b7 geboren in Shanghai, aufgewachsen in Japan", "lists": ["newcomers", "current"],
        "bio": "Die kanadische Pianistin zog im Alter von sieben Jahren nach Montreal, um bei dem legendären Chopin-Preisträger Dang Thai Son zu studieren. Kritiker beschreiben ihren Anschlag als „extrem klar, delikat und beinahe übernatürlich fließend“ (Le Monde).\n\n2023 debütierte sie mit dem Cleveland Orchestra, mittlerweile tritt sie regelmäßig mit dem NHK Symphony Orchestra und an Häusern wie dem Konzerthaus Berlin auf.",
        "awards": ["1. Preis, Ettlingen International Piano Competition", "1. Preis, Thomas & Evon Cooper International Competition (2023)", "Preisträgerin, Michelangeli-Wettbewerb"],
        "focus": ["Chopin", "Liszt", "Tschaikowsky", "Schubert"],
        "current_note": "Nach dem Cleveland-Debüt 2023 zunehmend gefragt bei japanischen und europäischen Orchestern.",
        "official_url": "https://sophialiu.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Sophia+Liu+pianist", "wikipedia_title": "Sophia Liu (pianist)",
    },
    {
        "slug": "anna-geniushene", "name": "Anna Geniushene", "flag": "\U0001F1F7\U0001F1FA",
        "born": "1991 \u00b7 Moskau", "lists": ["newcomers"],
        "bio": "International bekannt wurde sie 2022 mit der Silbermedaille beim Van Cliburn International Piano Competition in Fort Worth. Sie gilt als Spezialistin für das große russische Repertoire.\n\nSeit ihrem Cliburn-Erfolg konzertiert sie regelmäßig mit US-amerikanischen und europäischen Orchestern.",
        "awards": ["Silbermedaille, Van Cliburn International Piano Competition (2022)", "Finalistin, Sydney International Piano Competition"],
        "focus": ["Rachmaninow", "Prokofjew", "Liszt", "Beethoven"],
        "official_url": "https://en.wikipedia.org/wiki/Anna_Geniushene", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Anna+Geniushene+piano", "wikipedia_title": "Anna Geniushene",
    },
    {
        "slug": "kate-liu", "name": "Kate Liu", "flag": "\U0001F1FA\U0001F1F8",
        "born": "1994 \u00b7 geboren in Singapur, aufgewachsen in den USA", "lists": ["newcomers"],
        "bio": "Ihren internationalen Durchbruch schaffte sie 2015 beim Internationalen Chopin-Wettbewerb in Warschau, wo sie den dritten Preis sowie den Sonderpreis für die beste Mazurka gewann.\n\nSie wird von jüngeren Kolleginnen häufig als Vorbild genannt, unter anderem für ihre unverwechselbare Individualität auf der Bühne.",
        "awards": ["3. Preis + Mazurka-Preis, Chopin-Wettbewerb Warschau (2015)", "1. Preis, New York International Piano Competition"],
        "focus": ["Chopin", "Schubert", "Beethoven", "Brahms"],
        "official_url": "https://en.wikipedia.org/wiki/Kate_Liu", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Kate+Liu+Chopin+piano", "wikipedia_title": "Kate Liu (pianist)",
    },
    {
        "slug": "tiffany-poon", "name": "Tiffany Poon", "flag": "\U0001F1ED\U0001F1F0\U0001F1FA\U0001F1F8",
        "born": "1996 \u00b7 Hongkong", "lists": ["newcomers"],
        "bio": "Mit neun Jahren zog sie nach New York, um mit Vollstipendium an der Juilliard School zu studieren; parallel schloss sie ihr Studium an der Columbia University ab.\n\n2025 wurde sie mit dem Robert-Schumann-Preis der Stadt Zwickau ausgezeichnet.",
        "awards": ["1. Preis, Moscow International Chopin Competition for Young Pianists (2012)", "Robert-Schumann-Preis der Stadt Zwickau (2025)"],
        "focus": ["Schumann", "Debussy", "Ravel", "Chopin"],
        "official_url": "https://tiffanypoon.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/@TiffanyPoonPiano", "wikipedia_title": "Tiffany Poon",
    },
    {
        "slug": "beatrice-rana", "name": "Beatrice Rana", "flag": "\U0001F1EE\U0001F1F9",
        "born": "22. Januar 1993 \u00b7 Copertino, Italien", "lists": ["newcomers", "icons", "current"],
        "bio": "Eine der etabliertesten italienischen Pianistinnen ihrer Generation. Bekannt wurde sie durch ihren zweiten Preis beim Internationalen Chopin-Wettbewerb 2015; zuvor hatte sie bereits 2011, im Alter von 18 Jahren, den Montreal International Musical Competition gewonnen.\n\nSie konzertiert regelmäßig mit den führenden Orchestern der Welt und hat eine umfangreiche Diskografie bei Warner Classics.",
        "awards": ["2. Preis, Chopin-Wettbewerb Warschau (2015)", "1. Preis, Montreal International Musical Competition (2011)"],
        "focus": ["Bach", "Ravel", "Prokofjew", "Tschaikowsky"],
        "current_note": "Gehört 2025/26 zu den international meistgebuchten italienischen Solistinnen.",
        "official_url": "https://en.wikipedia.org/wiki/Beatrice_Rana", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Beatrice+Rana+piano", "wikipedia_title": "Beatrice Rana",
    },
    {
        "slug": "khatia-buniatishvili", "name": "Khatia Buniatishvili", "flag": "\U0001F1EC\U0001F1EA",
        "born": "1987 \u00b7 Tiflis", "lists": ["newcomers", "icons", "current"],
        "bio": "Eine der bekanntesten georgischen Pianistinnen weltweit, bekannt für ihre expressive, oft sehr freie Interpretationsweise. Sie gab bereits als Kind ihr Debüt mit Orchester und lebt heute in Paris.\n\nIhre Aufnahmen bei Sony Classical erreichen ein breites, auch klassik-fernes Publikum.",
        "awards": ["Finalistin, Internationaler Klavierwettbewerb Ferruccio Busoni", "Zahlreiche internationale Auszeichnungen für ihre Diskografie"],
        "focus": ["Liszt", "Rachmaninow", "Chopin", "Ravel"],
        "current_note": "Weiterhin eine der medienpräsentesten klassischen Pianistinnen mit weltweit ausverkauften Sälen.",
        "official_url": "https://en.wikipedia.org/wiki/Khatia_Buniatishvili", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Khatia+Buniatishvili+piano", "wikipedia_title": "Khatia Buniatishvili",
    },
    {
        "slug": "alice-sara-ott", "name": "Alice Sara Ott", "flag": "\U0001F1E9\U0001F1EA\U0001F1EF\U0001F1F5",
        "born": "1988 \u00b7 München", "lists": ["newcomers", "icons", "current"],
        "bio": "Tochter einer japanischen Mutter und eines deutschen Vaters, gilt sie als eine der vielseitigsten Pianistinnen ihrer Generation. Bekannt wurde sie unter anderem dadurch, dass sie gelegentlich barfuß auftritt.\n\nSeit ihrer MS-Diagnose 2019 spricht sie offen über die Krankheit und setzt sich öffentlich für das Thema Gesundheit im Musikbetrieb ein.",
        "awards": ["1. Preis, Concours International de Piano d'Île-de-France", "Echo Klassik-Preisträgerin"],
        "focus": ["Beethoven", "Debussy", "Grieg", "Liszt"],
        "current_note": "2025/26 mit vielbeachteten Recitals und Orchesterprojekten in Europa unterwegs.",
        "official_url": "https://en.wikipedia.org/wiki/Alice_Sara_Ott", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Alice+Sara+Ott+piano", "wikipedia_title": "Alice Sara Ott",
    },
    {
        "slug": "yuja-wang", "name": "Yuja Wang", "flag": "\U0001F1E8\U0001F1F3",
        "born": "1987 \u00b7 Peking", "lists": ["newcomers", "icons", "current"],
        "bio": "Zwar nicht mehr die jüngste, aber weiterhin die prägendste Pianistin ihrer Generation. Studierte am Curtis Institute bei Gary Graffman, ist heute Exklusivkünstlerin bei Deutsche Grammophon.\n\nBekannt für technische Extremvirtuosität kombiniert mit riskanten, hochenergetischen Interpretationen. Ihre Zusammenarbeit mit Gustavo Dudamel gilt als eine der prägendsten Solisten-Partnerschaften der Gegenwart.",
        "awards": ["Avery Fisher Career Grant", "Gramophone Artist of the Year (2021)"],
        "focus": ["Rachmaninow", "Prokofjew", "Liszt", "Ligeti"],
        "current_note": "Eine der international präsentesten Solistinnen überhaupt, mit dichtem Tourneeplan.",
        "official_url": "https://en.wikipedia.org/wiki/Yuja_Wang", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Yuja+Wang+piano", "wikipedia_title": "Yuja Wang",
    },
    {
        "slug": "marie-ange-nguci", "name": "Marie-Ange Nguci", "flag": "\U0001F1EB\U0001F1F7\U0001F1E6\U0001F1F1",
        "born": "1997/98 \u00b7 Frankreich (albanische Wurzeln)", "lists": ["newcomers", "current"],
        "bio": "In Albanien geboren, zog sie als Kind nach Frankreich und wurde mit 13 Jahren am Conservatoire National Supérieur de Paris aufgenommen. Neben ihrer Konzertkarriere promoviert sie musikwissenschaftlich.\n\nSie gilt als eine der vielseitigsten jungen Pianistinnen Europas und konzertiert regelmäßig bei der Philharmonie de Paris und dem Verbier Festival.",
        "awards": ["Stipendium der Fondation Banque Populaire", "Prix de la Fondation Safran"],
        "focus": ["Saint-Saëns", "Ravel", "Liszt", "Prokofjew"],
        "current_note": "Zunehmend gefragt bei großen europäischen Festivals.",
        "official_url": "https://en.wikipedia.org/wiki/Marie-Ange_Nguci", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Marie-Ange+Nguci+piano", "wikipedia_title": "Marie-Ange Nguci",
    },
    {
        "slug": "ying-li", "name": "Ying Li", "flag": "\U0001F1E8\U0001F1F3",
        "born": "1998/99 \u00b7 China", "lists": ["newcomers"],
        "bio": "Studierte am Curtis Institute of Music in Philadelphia und erzielte ihren internationalen Durchbruch als Preisträgerin sowohl beim Chopin-Wettbewerb als auch bei der Queen Elisabeth Competition.\n\nSie wird für ihre lyrische Ausdruckskraft und stilistische Vielseitigkeit geschätzt.",
        "awards": ["Preisträgerin, Queen Elisabeth Competition", "Preisträgerin, Internationaler Chopin-Wettbewerb"],
        "focus": ["Chopin", "Schumann", "Mozart", "Brahms"],
        "official_url": "https://en.wikipedia.org/wiki/Ying_Li_(pianist)", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Ying+Li+piano", "wikipedia_title": "Ying Li (pianist)",
    },
    {
        "slug": "yulianna-avdeeva", "name": "Yulianna Avdeeva", "flag": "\U0001F1F7\U0001F1FA",
        "born": "1985 \u00b7 Moskau", "lists": ["newcomers", "icons"],
        "bio": "Gewann 2010 als erste Frau seit Martha Argerich (1965) den Internationalen Chopin-Wettbewerb in Warschau. Bekannt für ihre intellektuelle Klarheit, konzertiert sie mit Orchestern wie den Berliner Philharmonikern.\n\nIhr Repertoire reicht bewusst über das übliche Chopin-Image hinaus bis zu Schostakowitschs Präludien und Fugen.",
        "awards": ["1. Preis, Chopin-Wettbewerb Warschau (2010)", "Preisträgerin, Concours de Genève"],
        "focus": ["Chopin", "Bach", "Schostakowitsch", "Beethoven"],
        "official_url": "https://en.wikipedia.org/wiki/Yulianna_Avdeeva", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Yulianna+Avdeeva+piano", "wikipedia_title": "Yulianna Avdeeva",
    },
    {
        "slug": "zlata-chochieva", "name": "Zlata Chochieva", "flag": "\U0001F1F7\U0001F1FA",
        "born": "1985 \u00b7 Moskau", "lists": ["newcomers", "icons"],
        "bio": "Gilt unter Berufsmusikern als „Pianistin für Pianisten“. Ihre Einspielungen von Rachmaninow und Chopin genießen unter Kennern Kultstatus.\n\nSie verbindet die klassische russische Klavierschule mit einer außergewöhnlich poetischen, nie forcierten Klanggestaltung.",
        "awards": ["Preisträgerin, Ferruccio-Busoni-Wettbewerb"],
        "focus": ["Rachmaninow", "Chopin", "Liszt", "Schumann"],
        "official_url": "https://en.wikipedia.org/wiki/Zlata_Chochieva", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Zlata+Chochieva+piano", "wikipedia_title": "Zlata Chochieva",
    },
    {
        "slug": "hj-lim", "name": "HJ Lim", "flag": "\U0001F1F0\U0001F1F7",
        "born": "1986 \u00b7 Südkorea", "lists": ["newcomers", "icons", "current"],
        "bio": "Wurde durch ihre komplette Einspielung aller 32 Beethoven-Klaviersonaten international bekannt. Studierte am Conservatoire National Supérieur de Paris.\n\nSie ist für einen unkonventionellen, mutigen Interpretationsstil bekannt und veröffentlicht auch Bücher über Musik und Interpretation.",
        "awards": ["Internationale Bestseller-Einspielung des Beethoven-Sonatenzyklus"],
        "focus": ["Beethoven", "Bach", "Liszt", "Schubert"],
        "current_note": "Bleibt durch ihre publizistische Tätigkeit und Konzerte medienpräsent.",
        "official_url": "https://en.wikipedia.org/wiki/HJ_Lim", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=HJ+Lim+piano", "wikipedia_title": "HJ Lim",
    },
    {
        "slug": "aimi-kobayashi", "name": "Aimi Kobayashi", "flag": "\U0001F1EF\U0001F1F5",
        "born": "1995 \u00b7 Japan", "lists": ["newcomers", "current"],
        "bio": "Begann mit drei Jahren Klavier zu spielen und trat schon als Siebenjährige mit Orchester auf. Weltweite Bekanntheit erlangte sie 2021 mit dem geteilten vierten Preis beim Internationalen Chopin-Wettbewerb.\n\nSie zählt heute zu den führenden Chopin-Interpretinnen ihrer Generation und konzertiert regelmäßig in Europa, Japan und Nordamerika.",
        "awards": ["4. Preis, Internationaler Chopin-Wettbewerb (2021)", "1. Preis, Asia-Pacific International Chopin Competition"],
        "focus": ["Chopin", "Mozart", "Beethoven", "Schumann"],
        "current_note": "Seit dem Chopin-Erfolg 2021 fest etabliert im internationalen Konzertbetrieb.",
        "official_url": "https://en.wikipedia.org/wiki/Aimi_Kobayashi", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Aimi+Kobayashi+piano", "wikipedia_title": "Aimi Kobayashi",
    },
    {
        "slug": "elisabeth-brauss", "name": "Elisabeth Brauß", "flag": "\U0001F1E9\U0001F1EA",
        "born": "1995 \u00b7 Deutschland", "lists": ["newcomers", "current"],
        "bio": "Studierte an der Hochschule für Musik, Theater und Medien Hannover und wurde von der BBC als New Generation Artist ausgewählt. Sie gastiert regelmäßig bei den BBC Proms und dem Lucerne Festival.\n\nKritiker heben besonders ihre intelligente Programmgestaltung hervor.",
        "awards": ["BBC New Generation Artist", "1. Preis, Kissinger KlavierOlymp"],
        "focus": ["Beethoven", "Schumann", "Brahms", "Prokofjew"],
        "current_note": "Eine der profiliertesten deutschen Pianistinnen ihrer Generation.",
        "official_url": "https://en.wikipedia.org/wiki/Elisabeth_Brau%C3%9F", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Elisabeth+Brau%C3%9F+piano", "wikipedia_title": "Elisabeth Brauß",
    },
    {
        "slug": "avery-gagliano", "name": "Avery Gagliano", "flag": "\U0001F1FA\U0001F1F8",
        "born": "2000/01 \u00b7 USA", "lists": ["newcomers"],
        "bio": "Zählt zu den wichtigsten amerikanischen Nachwuchspianistinnen. Gewann bereits als Teenager mehrere US-Wettbewerbe und verbindet technische Präzision mit natürlicher, kammermusikalischer Musikalität.\n\nSie wird regelmäßig für ihre ausgewogene, nie effekthascherische Interpretationsweise gelobt.",
        "awards": ["National YoungArts Winner", "Gewinnerin, Philadelphia Orchestra Greenfield Competition"],
        "focus": ["Beethoven", "Chopin", "Schumann", "Ravel"],
        "official_url": "https://en.wikipedia.org/wiki/Avery_Gagliano", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Avery+Gagliano+piano", "wikipedia_title": "Avery Gagliano",
    },
    {
        "slug": "isata-kanneh-mason", "name": "Isata Kanneh-Mason", "flag": "\U0001F1EC\U0001F1E7",
        "born": "27. Mai 1996 \u00b7 Nottingham, England", "lists": ["newcomers", "current"],
        "bio": "Älteste der sieben musikalischen Kanneh-Mason-Geschwister. Studierte an der Royal Academy of Music mit dem Sir-Elton-John-Stipendium, nachdem sie 2013 gemeinsam mit Elton John in Los Angeles aufgetreten war.\n\nIhr Debütalbum „Romance“ (2019, Decca) mit Werken von Clara Schumann debütierte auf Platz 1 der britischen Klassik-Charts. 2023 gab sie ihr Solo-Debüt bei den BBC Proms.",
        "awards": ["Leonard Bernstein Award, Schleswig-Holstein Musik Festival", "Opus Klassik – Nachwuchskünstlerin"],
        "focus": ["Clara Schumann", "Mendelssohn", "Prokofjew", "Gershwin"],
        "current_note": "Ihr neues Album „Prokofiev“ erschien im April 2026 bei Decca Classics; 2025/26 mit Duo-Tournee mit ihrem Bruder Sheku.",
        "official_url": "https://www.isatakannehmason.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Isata+Kanneh-Mason+piano", "wikipedia_title": "Isata Kanneh-Mason",
    },
    {
        "slug": "anna-fedorova", "name": "Anna Fedorova", "flag": "\U0001F1FA\U0001F1E6\U0001F1F3\U0001F1F1",
        "born": "27. Februar 1990 \u00b7 Kiew, Ukraine", "lists": ["newcomers", "current"],
        "bio": "Die ukrainisch-niederländische Pianistin wird als „Hauspianistin“ des Amsterdamer Concertgebouw bezeichnet. Ihre Live-Aufnahme von Rachmaninows 2. Klavierkonzert zählt mit über 45 Millionen Aufrufen zu den meistgesehenen klassischen Konzertaufnahmen auf YouTube.\n\nSeit der russischen Invasion 2022 organisiert sie Benefizkonzerte für die Ukraine.",
        "awards": ["1. Preis, Rubinstein-in-Memoriam-Wettbewerb (Polen 2009)", "14 internationale Wettbewerbspreise insgesamt"],
        "focus": ["Rachmaninow", "Chopin", "Ravel", "Skrjabin"],
        "current_note": "2025/26 mit neuem Album „Liberté“ sowie fortgesetztem Engagement für die Ukraine.",
        "official_url": "https://www.annafedorova.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Anna+Fedorova+piano", "wikipedia_title": "Anna Fedorova",
    },
    {
        "slug": "claire-huangci", "name": "Claire Huangci", "flag": "\U0001F1FA\U0001F1F8",
        "born": "22. März 1990 \u00b7 Rochester, USA", "lists": ["newcomers", "icons", "current"],
        "bio": "Studierte am Curtis Institute bei Gary Graffman (gemeinsam mit Yuja Wang) und danach in Hannover bei Arie Vardi. 2018 gewann sie den Concours Géza Anda. Lebt heute in Frankfurt am Main.\n\nIhre Diskografie reicht von Scarlatti-Gesamteinspielungen bis zu Werken von Komponistinnen wie Amy Beach und Florence Price.",
        "awards": ["1. Preis, Concours Géza Anda (2018)", "1. Preis, Chopin-Wettbewerb Darmstadt (2009) & Miami (2010)"],
        "focus": ["Scarlatti", "Chopin", "Rachmaninow", "Gershwin"],
        "current_note": "Dichter Orchester-Kalender 2025/26; neues Album „HEROINES“ (Alpha Classics, Januar 2026).",
        "official_url": "https://clairehuangci.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Claire+Huangci+piano", "wikipedia_title": "Claire Huangci",
    },
    {
        "slug": "zhang-zuo", "name": "Zhang Zuo (Zee Zee)", "flag": "\U0001F1E8\U0001F1F3",
        "born": "10. Oktober 1988 \u00b7 Shenzhen, China", "lists": ["newcomers", "icons", "current"],
        "bio": "Bekannt unter ihrem Künstlernamen „Zee Zee“. Begann mit fünf Jahren in Berlin Klavier zu spielen und studierte später am Eastman-Konservatorium sowie an der Juilliard School. War 2014/15 BBC New Generation Artist.\n\n2024 gründete sie das Kammermusikfestival Z+ in Shanghai.",
        "awards": ["1. Preis, Krainev International Piano Competition", "Juilliard William Petschek Piano Recital Award"],
        "focus": ["Liszt", "Ravel", "Wagner-Transkriptionen", "Mendelssohn"],
        "current_note": "Leitet 2025/26 erneut das Z+ Festival in Shanghai; parallel aktive Solokarriere in Europa und Asien.",
        "official_url": "https://www.zeezee-piano.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Zhang+Zuo+Zee+Zee+piano", "wikipedia_title": "Zhang Zuo (pianist)",
    },
    {
        "slug": "yeol-eum-son", "name": "Yeol Eum Son", "flag": "\U0001F1F0\U0001F1F7",
        "born": "2. Mai 1986 \u00b7 Wonju, Südkorea", "lists": ["newcomers", "icons", "current"],
        "bio": "Gewann die Silbermedaille sowohl beim Van Cliburn International Piano Competition (2009) als auch beim Internationalen Tschaikowsky-Wettbewerb (2011). Ihre YouTube-Aufnahme von Mozarts Klavierkonzert Nr. 21 gilt mit über 30 Millionen Aufrufen als meistgesehene Live-Mozart-Aufnahme der Plattform.\n\nSie lebt in Hannover.",
        "awards": ["Silbermedaille, Van Cliburn International Piano Competition (2009)", "Silbermedaille, Internationaler Tschaikowsky-Wettbewerb (2011)"],
        "focus": ["Mozart", "Beethoven", "Rachmaninow", "Ravel"],
        "current_note": "2025/26-Saison mit London Philharmonic und BBC Symphony Orchestra; neues Album mit beiden Ravel-Klavierkonzerten (Naïve, 2026).",
        "official_url": "http://www.yeoleumson.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Yeol+Eum+Son+piano", "wikipedia_title": "Yeol Eum Son",
    },
    {
        "slug": "nathalia-milstein", "name": "Nathalia Milstein", "flag": "\U0001F1EB\U0001F1F7",
        "born": "1995 \u00b7 Lyon, Frankreich", "lists": ["newcomers", "current"],
        "bio": "Stammt aus einer russisch-französischen Musikerfamilie und erhielt mit vier Jahren ihre ersten Klavierstunden von ihrem Vater. Studierte bei Nelson Goerner in Genf und danach bei András Schiff in Berlin.\n\nSeit Jahren bildet sie ein Duo mit ihrer Schwester, der Geigerin Maria Milstein.",
        "awards": ["1. Preis, Dublin International Piano Competition (2015)", "Prix Jeune Soliste, Médias Francophones Publics (2017)"],
        "focus": ["Prokofjew", "Ravel", "Schumann", "Tschaikowsky"],
        "current_note": "Drittes Soloalbum „Alla Schumann“ erschien im November 2025; 2025/26 mit Debüt am Concertgebouw (großer Saal).",
        "official_url": "https://www.nathaliamilstein.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Nathalia+Milstein+piano", "wikipedia_title": "Nathalia Milstein",
    },
    {
        "slug": "rachel-cheung", "name": "Rachel Cheung", "flag": "\U0001F1ED\U0001F1F0",
        "born": "27. September 1991 \u00b7 Hongkong", "lists": ["newcomers", "current"],
        "bio": "Studierte an der Hong Kong Academy for Performing Arts und an der Yale School of Music bei Peter Frankl. Finalistin und Publikumspreisträgerin des Van Cliburn International Piano Competition 2017.\n\n2025 gründete sie die Rachel Cheung Music Academy in Hongkong.",
        "awards": ["Publikumspreis, Van Cliburn International Piano Competition (2017)", "5. Preis, Leeds International Pianoforte Competition (2009)"],
        "focus": ["Chopin", "Ravel", "Beethoven", "Zeitgenössisches Repertoire"],
        "current_note": "2023 erschien ihr internationales Debütalbum „Reflections“ bei Decca; seit 2025 zusätzlich Akademiegründerin.",
        "official_url": "https://www.rachelcheung.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Rachel+Cheung+piano", "wikipedia_title": "Rachel Cheung",
    },
    {
        "slug": "martha-argerich", "name": "Martha Argerich", "flag": "\U0001F1E6\U0001F1F7",
        "born": "1941 \u00b7 Buenos Aires, Argentinien", "lists": ["icons", "current"],
        "bio": "Weithin als eine der größten Pianistinnen aller Zeiten anerkannt. Gab ihr Debütkonzert mit acht Jahren und gewann 1965 den Internationalen Chopin-Wettbewerb in Warschau.\n\nBerühmt für ihre elektrisierende, spontane Spielweise, ihre Vorliebe für Kammermusik und ihre langjährige Förderung junger Pianistinnen und Pianisten.",
        "awards": ["1. Preis, Internationaler Chopin-Wettbewerb Warschau (1965)", "Zahlreiche Grammy Awards", "Praemium Imperiale"],
        "focus": ["Chopin", "Prokofjew", "Ravel", "Schumann", "Kammermusik"],
        "current_note": "Weiterhin aktiv im Konzertbetrieb, insbesondere in der Kammermusik; regelmäßige Auftritte bei ihrem eigenen Festival.",
        "official_url": "https://en.wikipedia.org/wiki/Martha_Argerich", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Martha+Argerich+piano", "wikipedia_title": "Martha Argerich",
    },
    {
        "slug": "mitsuko-uchida", "name": "Mitsuko Uchida", "flag": "\U0001F1EF\U0001F1F5\U0001F1EC\U0001F1E7",
        "born": "1948 \u00b7 Tokio, Japan", "lists": ["icons", "current"],
        "bio": "Gilt als eine der bedeutendsten Interpretinnen von Mozart, Schubert und Beethoven ihrer Generation. Lebt seit ihrer Jugend in London und ist Exklusivkünstlerin bei Decca Classics.\n\nIhre Gesamteinspielungen der Mozart-Klavierkonzerte und -Sonaten gelten als Referenzaufnahmen. Sie ist zudem künstlerische Co-Leiterin des Marlboro Music Festivals.",
        "awards": ["Praemium Imperiale", "Mehrere Grammy-Nominierungen", "Ehrendoktorwürden mehrerer Universitäten"],
        "focus": ["Mozart", "Schubert", "Beethoven", "Schönberg"],
        "current_note": "Saison 2026/27 mit den Wiener Philharmonikern unter Riccardo Muti sowie Recitals in Berlin, Wien, London und New York.",
        "official_url": "https://mitsukouchida.com/", "official_label": "Offizielle Website",
        "youtube": "https://www.youtube.com/results?search_query=Mitsuko+Uchida+piano", "wikipedia_title": "Mitsuko Uchida",
    },
    {
        "slug": "helene-grimaud", "name": "Hélène Grimaud", "flag": "\U0001F1EB\U0001F1F7",
        "born": "1969 \u00b7 Aix-en-Provence, Frankreich", "lists": ["icons"],
        "bio": "Bekannt für ihre intensiven, dunkel timbrierten Interpretationen von Rachmaninow, Brahms und Schumann. Studierte am Pariser Conservatoire und wurde früh von Daniel Barenboim gefördert.\n\nNeben der Musikkarriere ist sie Naturschützerin: Sie gründete das Wolf Conservation Center im US-Bundesstaat New York.",
        "awards": ["Victoire de la Musique", "Zahlreiche internationale Schallplattenpreise"],
        "focus": ["Rachmaninow", "Brahms", "Schumann", "Ravel"],
        "official_url": "https://en.wikipedia.org/wiki/H%C3%A9l%C3%A8ne_Grimaud", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=H%C3%A9l%C3%A8ne+Grimaud+piano", "wikipedia_title": "Hélène Grimaud",
    },
    {
        "slug": "maria-joao-pires", "name": "Maria João Pires", "flag": "\U0001F1F5\U0001F1F9",
        "born": "1944 \u00b7 Lissabon, Portugal", "lists": ["icons"],
        "bio": "Eine der bedeutendsten Mozart- und Schubert-Interpretinnen ihrer Generation, bekannt für ihren zurückhaltenden, nie effekthaschenden Anschlag. Gab bereits mit sieben Jahren ihr erstes öffentliches Konzert.\n\nSie gründete mehrere musikpädagogische Initiativen und zog sich zeitweise bewusst aus dem großen Konzertbetrieb zurück, um sich der Musikvermittlung zu widmen.",
        "awards": ["Grand Prix du Disque", "Ehrenmedaille des Europäischen Parlaments für kulturelles Engagement"],
        "focus": ["Mozart", "Schubert", "Chopin", "Beethoven"],
        "official_url": "https://en.wikipedia.org/wiki/Maria_Jo%C3%A3o_Pires", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Maria+Jo%C3%A3o+Pires+piano", "wikipedia_title": "Maria João Pires",
    },
    {
        "slug": "angela-hewitt", "name": "Angela Hewitt", "flag": "\U0001F1E8\U0001F1E6",
        "born": "1958 \u00b7 Ottawa, Kanada", "lists": ["icons"],
        "bio": "International vor allem für ihre Bach-Interpretationen bekannt; ihre Gesamteinspielung von Bachs Klavierwerken für Hyperion Records gilt als eine der wichtigsten Referenzaufnahmen. Stammt aus einer Organistenfamilie.\n\nSie gründete das Trasimeno Music Festival in Italien und ist als Pädagogin ebenso gefragt wie als Konzertpianistin.",
        "awards": ["Bach-Preis der Stadt Leipzig", "Officer of the Order of Canada"],
        "focus": ["Bach", "Couperin", "Rameau", "Beethoven"],
        "official_url": "https://en.wikipedia.org/wiki/Angela_Hewitt", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Angela+Hewitt+Bach+piano", "wikipedia_title": "Angela Hewitt",
    },
    {
        "slug": "elisabeth-leonskaja", "name": "Elisabeth Leonskaja", "flag": "\U0001F1EC\U0001F1EA\U0001F1E6\U0001F1F9",
        "born": "1945 \u00b7 Tiflis, Georgien", "lists": ["icons"],
        "bio": "Eine der letzten großen Vertreterinnen der russischen Klavierschule der Nachkriegsgeneration, geprägt durch ihre enge künstlerische Verbindung zu Swjatoslaw Richter. Verließ 1978 die Sowjetunion und lebt seither in Wien.\n\nBekannt für ihre unaufgeregte, tief durchdachte Spielweise, insbesondere in Schubert und Brahms.",
        "awards": ["Robert-Schumann-Preis der Stadt Zwickau", "Österreichisches Ehrenkreuz für Wissenschaft und Kunst"],
        "focus": ["Schubert", "Brahms", "Schumann", "Tschaikowsky"],
        "official_url": "https://en.wikipedia.org/wiki/Elisabeth_Leonskaja", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Elisabeth+Leonskaja+piano", "wikipedia_title": "Elisabeth Leonskaja",
    },
    {
        "slug": "gabriela-montero", "name": "Gabriela Montero", "flag": "\U0001F1FB\U0001F1EA",
        "born": "1970 \u00b7 Caracas, Venezuela", "lists": ["icons"],
        "bio": "Einzigartig unter den international führenden Konzertpianistinnen für ihre Fähigkeit zur klassischen Improvisation: Sie entwickelt live über vom Publikum vorgeschlagene Melodien komplette Variationen im Stil großer Komponisten.\n\nSie engagiert sich politisch für Menschenrechte in Venezuela und komponiert eigene Werke, die sich mit politischer Gewalt auseinandersetzen.",
        "awards": ["Latin Grammy Award", "Vertrag mit Orchid Classics als Improvisationskünstlerin und Komponistin"],
        "focus": ["Improvisation", "Rachmaninow", "Eigene Kompositionen", "Chopin"],
        "official_url": "https://en.wikipedia.org/wiki/Gabriela_Montero", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Gabriela+Montero+improvisation+piano", "wikipedia_title": "Gabriela Montero",
    },
    {
        "slug": "lise-de-la-salle", "name": "Lise de la Salle", "flag": "\U0001F1EB\U0001F1F7",
        "born": "1988 \u00b7 Cherbourg, Frankreich", "lists": ["icons"],
        "bio": "Gab bereits mit neun Jahren ihr Debüt im französischen Rundfunk und unterschrieb mit 13 Jahren ihren ersten Plattenvertrag. Studierte am Conservatoire de Paris.\n\nSie ist bekannt für kraftvolle, intellektuell durchdachte Interpretationen, insbesondere von Prokofjew und Bartók.",
        "awards": ["Preisträgerin, Young Concert Artists International Auditions New York", "Diapason d'Or mehrfach"],
        "focus": ["Prokofjew", "Bartók", "Beethoven", "Rachmaninow"],
        "official_url": "https://en.wikipedia.org/wiki/Lise_de_la_Salle", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Lise+de+la+Salle+piano", "wikipedia_title": "Lise de la Salle",
    },
    {
        "slug": "simone-dinnerstein", "name": "Simone Dinnerstein", "flag": "\U0001F1FA\U0001F1F8",
        "born": "1972 \u00b7 New York, USA", "lists": ["icons"],
        "bio": "Wurde durch ihre 2007 in Eigenregie finanzierte Einspielung von Bachs Goldberg-Variationen bekannt, die zu einem der meistverkauften klassischen Debütalben der 2000er-Jahre wurde.\n\nSie gilt seither als eine der eigenständigsten Bach-Interpretinnen ihrer Generation und initiierte das Bildungsprojekt „Neighborhood Classics“.",
        "awards": ["Billboard-Charterfolg mit dem Goldberg-Variationen-Debütalbum (2007)"],
        "focus": ["Bach", "Schubert", "Philip Glass", "Beethoven"],
        "official_url": "https://en.wikipedia.org/wiki/Simone_Dinnerstein", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Simone+Dinnerstein+Bach+piano", "wikipedia_title": "Simone Dinnerstein",
    },
    {
        "slug": "olga-kern", "name": "Olga Kern", "flag": "\U0001F1F7\U0001F1FA\U0001F1FA\U0001F1F8",
        "born": "1975 \u00b7 Moskau, Russland", "lists": ["icons"],
        "bio": "Gewann 2001 als erste Frau seit über 30 Jahren die Goldmedaille des Van Cliburn International Piano Competition. Ist eine direkte Nachfahrin des Komponisten Konstantin Igumnow.\n\nHeute lebt sie in den USA, unterrichtet als Professorin und leitet mehrere amerikanische Klavierfestivals.",
        "awards": ["Goldmedaille, Van Cliburn International Piano Competition (2001)", "Grammy Award"],
        "focus": ["Rachmaninow", "Chopin", "Skrjabin", "Tschaikowsky"],
        "official_url": "https://en.wikipedia.org/wiki/Olga_Kern", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Olga+Kern+piano", "wikipedia_title": "Olga Kern",
    },
    {
        "slug": "clara-schumann", "name": "Clara Schumann", "flag": "\U0001F1E9\U0001F1EA",
        "born": "1819\u20131896 \u00b7 Leipzig, Deutschland", "lists": ["icons"],
        "bio": "Eine der einflussreichsten Pianistinnen des 19. Jahrhunderts und Wegbereiterin für Generationen von Musikerinnen. Bereits als Kind ein gefeiertes Wunderkind, setzte sie sich zeit ihres Lebens für das Werk ihres Mannes Robert Schumann und ihres Freundes Johannes Brahms ein.\n\nSie war zugleich eine bedeutende Komponistin, deren eigenes Schaffen erst in den letzten Jahrzehnten die verdiente Aufmerksamkeit erhalten hat.",
        "awards": ["Königlich-Preußische Hofpianistin", "Prägende Konzertkarriere über mehr als 60 Jahre"],
        "focus": ["Robert Schumann", "Brahms", "Chopin", "Eigene Kompositionen"],
        "official_url": "https://en.wikipedia.org/wiki/Clara_Schumann", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Clara+Schumann+piano+works", "wikipedia_title": "Clara Schumann",
    },
    {
        "slug": "alicia-de-larrocha", "name": "Alicia de Larrocha", "flag": "\U0001F1EA\U0001F1F8",
        "born": "1923\u20132009 \u00b7 Barcelona, Spanien", "lists": ["icons"],
        "bio": "Die bedeutendste Interpretin des spanischen Klavierrepertoires im 20. Jahrhundert, weltberühmt für ihre Einspielungen von Albéniz, Granados und Falla. Trotz ungewöhnlich kleiner Hände entwickelte sie eine außergewöhnliche Technik.\n\nSie konzertierte über sieben Jahrzehnte hinweg weltweit und gilt bis heute als Referenz für die spanische Klaviermusik.",
        "awards": ["Mehrfache Grammy Awards", "Praemium Imperiale", "UNESCO-Preis für Musik"],
        "focus": ["Albéniz", "Granados", "Falla", "Mozart"],
        "official_url": "https://en.wikipedia.org/wiki/Alicia_de_Larrocha", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Alicia+de+Larrocha+Albeniz+piano", "wikipedia_title": "Alicia de Larrocha",
    },
    {
        "slug": "clara-haskil", "name": "Clara Haskil", "flag": "\U0001F1F7\U0001F1F4\U0001F1E8\U0001F1ED",
        "born": "1895\u20131960 \u00b7 Bukarest, Rumänien", "lists": ["icons"],
        "bio": "Eine der verehrtesten Mozart-Interpretinnen der Musikgeschichte, deren Karriere lange von gesundheitlichen Rückschlägen und einer schweren Skoliose-Erkrankung überschattet war. Erst nach dem Zweiten Weltkrieg erlangte sie die internationale Anerkennung, die ihr künstlerisch längst gebührte.\n\nIhr nach ihr benanntes Festival und ein internationaler Klavierwettbewerb in Vevey, Schweiz, halten ihr Andenken bis heute lebendig.",
        "awards": ["Grand Prix du Disque (mehrfach, posthum)", "Namensgeberin des Concours Clara Haskil"],
        "focus": ["Mozart", "Beethoven", "Schumann", "Kammermusik"],
        "official_url": "https://en.wikipedia.org/wiki/Clara_Haskil", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Clara+Haskil+Mozart+piano", "wikipedia_title": "Clara Haskil",
    },
    {
        "slug": "myra-hess", "name": "Myra Hess", "flag": "\U0001F1EC\U0001F1E7",
        "born": "1890\u20131965 \u00b7 London, Großbritannien", "lists": ["icons"],
        "bio": "Britische Pianistin, die während des Zweiten Weltkriegs berühmt für die täglichen Mittagskonzerte in der National Gallery in London wurde — über tausend Konzerte als kulturelle Trotzreaktion gegen den Bombenkrieg.\n\nFür dieses Engagement wurde sie 1941 zur „Dame Commander of the British Empire“ ernannt. Ihre Bach-Transkription „Jesu, Joy of Man's Desiring“ zählt bis heute zu den bekanntesten Klavierarrangements überhaupt.",
        "awards": ["Dame Commander of the British Empire (1941)"],
        "focus": ["Bach", "Beethoven", "Schumann", "Brahms"],
        "official_url": "https://en.wikipedia.org/wiki/Myra_Hess", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Myra+Hess+piano", "wikipedia_title": "Myra Hess",
    },
    {
        "slug": "annie-fischer", "name": "Annie Fischer", "flag": "\U0001F1ED\U0001F1FA",
        "born": "1914\u20131995 \u00b7 Budapest, Ungarn", "lists": ["icons"],
        "bio": "Eine der bedeutendsten Beethoven-Interpretinnen des 20. Jahrhunderts, bekannt für ihre kompromisslose künstlerische Ehrlichkeit — sie verweigerte jahrzehntelang die Veröffentlichung ihrer Beethoven-Sonaten-Gesamtaufnahme, weil sie mit dem Ergebnis nicht restlos zufrieden war.\n\nSie überlebte den Zweiten Weltkrieg im schwedischen Exil und kehrte danach nach Budapest zurück.",
        "awards": ["Kossuth-Preis", "Mehrfache internationale Schallplattenpreise (postum)"],
        "focus": ["Beethoven", "Schumann", "Liszt", "Bartók"],
        "official_url": "https://en.wikipedia.org/wiki/Annie_Fischer", "official_label": "Wikipedia-Profil",
        "youtube": "https://www.youtube.com/results?search_query=Annie+Fischer+Beethoven+piano", "wikipedia_title": "Annie Fischer",
    },
]

# Kuratierte Reihenfolge fuer die "current"-Ansicht (Top 20, Stand Juli 2026).
CURRENT_ORDER = [
    "isata-kanneh-mason", "nathalia-milstein", "yeol-eum-son", "mitsuko-uchida",
    "martha-argerich", "rachel-cheung", "claire-huangci", "zhang-zuo",
    "anna-fedorova", "alexandra-dovgan", "eva-gevorgyan", "sophia-liu",
    "hj-lim", "beatrice-rana", "alice-sara-ott", "yuja-wang",
    "khatia-buniatishvili", "marie-ange-nguci", "elisabeth-brauss", "aimi-kobayashi",
]
